### PR TITLE
Compatibility with redux-observable 0.16.0

### PR DESCRIPTION
**Pull request by actra-gschuster**
Method signature changed in redux-observable 0.16.0, adapted for decorator

### CODE REVIEW

**Comment by e-schultz** [comment]
@actra-gschuster didn't see this PR came in and I was just about to do the same :)

**Comment by actra-gschuster** [comment]
:-)
I also updated the dependencies, they where way outdated, hope that's OK.

**Comment by tcozzens** [comment]
@actra-gschuster @e-schultz 

hey there guys,

I am looking to upgrade redux-observable to the latest package, but this repo is behind. Just curious if this is going to be looked at or if something else should be done as regards to this "failing"

Any feedback would be appreciated!

**Comment by e-schultz** [comment]
@tcozzens - upgrading to redux-observable 0.17 or 0.18 should still be fine (might get complaints about unmet peer dependency)  - don't see any breaking changes, I've just been a bit more on the defensive side with peer deps.

I should be able to do a publish upgrading the peer deps on this before end of week

**Comment by tcozzens** [comment]
@e-schultz any update on this?

**Comment by smithad15** [comment]
Looks like this has been resolved in `master`

**Pull request closed without merging**
