### PR TITLE
Angular v6 update

### PR DESCRIPTION
**Pull request by alexislargaiolli**
* Update angular modules to v6
     * Update redux to v4
     * Update redux-observable to v1
     * Update rxjs to v6
     * Update createEpics to be comptatible with rxjs 6
     * createEpics now return a rootEpic that can be used in epicMiddleware.run(rootEpic); (https://redux-observable.js.org/docs/api/createEpicMiddleware.html)
     * Remove option support in createEpics method because option can be passed to epicMiddleware.run with root epic return by createEpics
     * Update unit tests

### CODE REVIEW

**Comment by alexislargaiolli** [comment]
Hi !

I forgot to mention that there are breaking changes. createEpics need to be use that way :
```typescript
const epicMiddleware = createEpicMiddleware();
store.configureStore(
      reducers,
      {},
      [
        epicMiddleware
      ],
      devTools.isEnabled() ? [devTools.enhancer()] : []
    );
epicMiddleware.run(createEpics(...));
```
And epicMiddleware.run can take options directly.

I tried this update in an angular 6 project and it work like a charm.

**Comment by e-schultz** [comment]
Hi @alexislargaiolli  - thanks for taking a look at this. I've been away from Angular projects for a few months, I'll try and take a look at this soon and see if I can get it merged in / published.

**Comment by alexislargaiolli** [comment]
Hi @e-schultz ! You welcome ! Thank you for this useful tiny lib.

The tests pass but the CI fails for another reason.

**Comment by jamesbs** [comment]
Thank you for the effort but closing this in favour of #21

**Pull request closed without merging**
